### ISSUE TITLE
more_building_info mod crash

### ISSUE THREAD

**Issue by mrstoned-gh** [yobbobandana/oni_mods#1]
Attached is file with error-message.
[crash_more-building-info.txt](https://github.com/yobbobandana/oni_mods/files/7271833/crash_more-building-info.txt)

**Comment by yobbobandana** [comment]
wow, Klei actually messed with that just last week... what are the chances...

thanks for the report :) this will be fixed in a few days when Klei releases the next stable version. I'll see if i can come up with an interim solution but if not i'll just have to mark it incompatible until then

**Comment by yobbobandana** [comment]
fixed in v0.2. Not sure how reliably steam keeps things up to date, but it updated instantly for me. Should work on both stable and public_testing branches now.
